<?php

namespace AppBundle\Repository;

/**
 * critiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class critiqueRepository extends \Doctrine\ORM\EntityRepository
{

}
