<?php

namespace AppBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findOneById($id)
    {
        $qb=$this->createQueryBuilder('m');
        $qb->addSelect('m')
            ->andWhere('m.movie_id = $id');
        $query=$qb->getQuery();
        $results=$query->getResult();

        return $results;

    }

}
