home:
    path:     /
    defaults: { _controller: AppBundle:Film:home }

detail:
    path:   /détails/{id}
    defaults: { _controller: AppBundle:Film:detail}

login:
    path:   /login
    defaults: { _controller:AppBundle:Film:login}

register:
    path:   /register
    defaults: { _controller:AppBundle:Film:register}

logout:
    path:   /deconnexion
    defaults: { _controller:AppBundle:Film:register}

comment:
    path:   /commentaire
    defaults: { _controller:AppBundle:Film:comment}

people:
    path:   /people/{id}
    defaults: { _controller:AppBundle:Film:people}

resultatRecherche:
    path:   /resultat
    defaults: { _controller:AppBundle:Film:resultatRecherche}

