# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
                    entity:
                        class: AppBundle\Entity\app_user
                        property: username


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home

    encoders:
            AppBundle\Entity\app_user:
                algorithm: bcrypt
                cost: 13
